package app;

public enum ActionStatus {
    SUCCESS, SUCCESS_VIEW, SUCCESS_FAVORITE, INVALID_FAVORITE, ALREADY_FAVORITE, SUCCESS_RATING,
    INVALID_RATING, ALREADY_RATED, POPULAR_NOT_PREMIUM, FAVORITE_NOT_PREMIUM, SEARCH_NOT_PREMIUM
}
